name: Docs validation

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate-docs:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v4
      - name: Validate Docs
        uses: hazelcast/hazelcast-docs/.github/actions/validate@main
        with:
          check-links-loader-log-level: debug
          orphan-checker-log-failure-level: skip
          orphan-checker-directory: tutorials
